import com.SE459.SensorsCollection.MapManipulator;
import com.SE459.SensorsCollection.SensorsCollection;

import java.util.LinkedList;
import java.util.List;

/*
Initiate a sensorsCollection object to generate a basic layout json file.
If one wants to change the basic map, initiate a mapManipulator object that has two primary functions,
one is openOrCloseDoor whose parameters format as x-(x*10+y*10)/2 -close(open) or (x*10+y*10)/2 -y-close(open)
, which depends on whether the door goes through horizontally or vertically
after all, call the function runFinalMap() from the object sensorCollection so that the changed layout json file will
cover the previous one.
As shown below, the door in the guest bedroom A is closed after write in the cmd "6-35-close", so the robot will only clean
the guest bedroomA.
 */
public class main {

    //test
    public static void main(String[] args) {

        SensorsCollection s = new SensorsCollection();

        //after calling the function  s.generateBasicMap(1), there will be a json file(representing the basic map) showing up
        //in the same layer as the maven.xml.
        s.generateBasicMap(1);


        MapManipulator m = new MapManipulator(s.getMapArch());

        //close the door in the Guest Bedroom A
        List<String> cmd = new LinkedList<>();
        cmd.add("6-35-close");
        m.openOrCloseDoor(cmd);

        //generate the changed map and the changed json file will cover the previous one that was generated by s.generateBasicMap(1)
        s.runFinalMap();
        s.clean();

    }

}
